packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@clerk/shared': true
  '@prisma/engines': true
  '@sentry/cli': true
  bufferutil: true
  core-js: true
  core-js-pure: true
  esbuild: true
  prisma: true
  sharp: true
minimumReleaseAgeExclude:
  - '@ai-sdk/gateway@4.0.76'
  - '@ai-sdk/openai@4.0.62 || 4.0.63'
  - '@ai-sdk/provider-utils@5.0.37'
  - '@ai-sdk/provider@4.0.11'
  - '@arcjet/analyze-wasm@1.12.0'
  - '@arcjet/analyze@1.12.0'
  - '@arcjet/body@1.12.0'
  - '@arcjet/cache@1.12.0'
  - '@arcjet/duration@1.12.0'
  - '@arcjet/env@1.12.0'
  - '@arcjet/headers@1.12.0'
  - '@arcjet/ip@1.12.0'
  - '@arcjet/logger@1.12.0'
  - '@arcjet/next@1.12.0'
  - '@arcjet/protocol@1.12.0'
  - '@arcjet/runtime@1.12.0'
  - '@arcjet/skills@1.12.0'
  - '@arcjet/sprintf@1.12.0'
  - '@arcjet/stable-hash@1.12.0'
  - '@arcjet/transport@1.12.0'
  - '@nosecone/next@1.12.0'
  - '@vercel/cli-config@0.2.5'
  - ai@7.0.94 || 7.0.95
  - arcjet@1.12.0
  - flags@4.3.1
  - lucide-react@1.43.0
  - nosecone@1.12.0
  - posthog-js@1.428.8 || 1.428.9
  - react-email@6.9.5
  - '@posthog/core@1.51.2'
  - '@posthog/types@1.409.3'
  - ultracite@7.11.1
  - import-in-the-middle@3.5.0
  - nypm@0.6.10
  - posthog-node@5.51.8
